const express = require('express');
const getpost = express.Router();
const validateBlogPost = require("../middleware/validateBlogPost");
const GetAllposts = require("../controlers/GetAllposts");
const ControlAddRemoveLikes = require("../controlers/ControlAddRemoveLikes");
const getThisUser = require("../controlers/getThisUser");
const validateOnlyUserPost = require("../middleware/validateOnlyUserPost");
const GetOnlyUserPosts = require("../controlers/GetOnlyUserPosts");
const controlComments = require("../controlers/controlComments");
getpost.get("/BlogPosts/:id",validateBlogPost,GetAllposts);
getpost.get("/userProfile/:id",getThisUser);
getpost.post("/BlogPost/like/:id",validateBlogPost,ControlAddRemoveLikes);
getpost.post("/BlogPost/comment/:id",validateBlogPost,controlComments.controlComments);
getpost.get("/BlogPost/showcomments/:postId",validateBlogPost,controlComments.showcomments);
getpost.post("/BlogPost/commentDelete/:id",validateBlogPost,controlComments.deleteComment);
getpost.get("/OnlyUserPosts/:id",validateOnlyUserPost,GetOnlyUserPosts);
module.exports = getpost;